GENERIC_PRAISE = [
    "This is well explained",
    "Enjoyed listening to this",
    "Awesome channel",
    "Strong throughout",
    "Good production",
    "Easy to listen to",
    "Nice sound",
    "Easy replay",
    "The vibes are great",
    "Great pacing",
    "This video is very good",
    "This is very helpful",
    "Well polished",
    "Excellent musicality",
    "This track is solid",
    "Excellent content",
    "Enjoyed watching this",
    "Drums sound great",
    "Kept me listening",
    "Exceeded expectations",
    "Glad I found this",
    "Very good content",
    "Great craftsmanship",
    "Well written",
    "Nicely structured",
    "Very musical",
    "Well mixed",
    "Nicely done overall",
    "Great stuff",
    "Nicely done musically",
    "This song is well done",
    "Very impressive",
    "Melody is beautiful",
    "Very well put together",
    "Everything makes sense",
    "Good editing",
    "Great energy",
    "Lyrics work well",
    "Overall excellent",
    "Nice drums",
    "Amazing album",
    "Great voice",
    "Positive energy",
    "Really nice song",
    "Sound quality is good",
    "Solid lyrics",
    "This song is solid",
    "Great channel",
    "Music is great",
    "Everything is clear",
    "Nice and smooth",
    "Nice style",
    "Great arrangement",
    "Thanks for explaining",
    "This is well done",
    "Amazing listen",
    "Musically pleasing",
    "Very helpful",
    "Good voiceover",
    "Consistently good content",
    "Really enjoyed this song",
    "Nicely done",
    "Creative sound design",
    "Clean production",
    "Good music choice",
    "Overall very good",
    "Very crisp",
    "Nice atmosphere",
    "Underrated project",
    "Looks professional",
    "Nice voice",
    "Nice listen",
    "Great for late nights",
    "Clear narration",
    "Clean vocals",
    "Curated well",
    "Nice songwriting",
    "Everything sounds great",
    "Helped me a lot",
    "Perfect vibe music",
    "Awesome work",
    "Nice visuals",
    "Well structured",
    "Beat goes hard",
    "This was amazing",
    "Nice originality",
    "Easy to understand",
    "Sets a great mood",
    "Nice arrangement",
    "Good atmosphere",
    "You can tell effort went into this",
    "Editing is great",
    "Nice presentation",
    "Smooth track",
    "Creative track",
    "Great DJ mix",
    "This is excellent overall",
    "Mix sounds clean",
    "Great track",
    "Track selection is great",
    "Great selection",
    "Solid drums",
    "Never gets old",
    "Good overall execution",
    "Loved this song",
    "No skips",
    "Underrated content",
    "Great content",
    "Nice pacing",
    "Really solid video",
    "Very well executed",
    "Mastering sounds great",
    "Solid track",
    "This song is awesome",
    "Very solid work",
    "Great for chilling",
    "This video is great",
    "Well mastered",
    "Amazing track",
    "Glad I watched this",
    "This is easy to follow",
    "Great listen",
    "Great explanation",
    "Very relaxing",
    "Interesting sound",
    "Good vibes",
    "Replay value is high",
    "Really impressive",
    "Groove is great",
    "Awesome video",
    "Awesome track",
    "Excellent sound design",
    "Awesome job",
    "Deserves more attention",
    "Great chord progression",
    "Definitely worth watching",
    "This is nicely done",
    "Kept me engaged",
    "Interesting from start to finish",
    "Everything is clear and clean",
    "This is really good",
    "Good pacing and flow",
    "Great breakdown",
    "Great songwriting",
    "Sounds professional",
    "Another great release",
    "Solid work",
    "Very smooth delivery",
    "Audio is clear",
    "Vocals sound great",
    "Relaxing mix",
    "Loved this video",
    "Excellent visuals",
    "Great structure",
    "Nice soundscape",
    "Excellent presentation",
    "Pulled me in",
    "Nice low end",
    "Solid beat",
    "Job well done",
    "Good job",
    "Thanks for the video",
    "Nice chord progression",
    "Helpful video",
    "Album sounds great",
    "This should have more views",
    "Good clear explanation",
    "Put together nicely",
    "Great album",
    "Overall solid release",
    "Nice rhythm",
    "Lovely melody",
    "Great beat",
    "Overall solid video",
    "Well presented",
    "Bass hits nicely",
    "Interesting video",
    "Nicely polished",
    "Amazing mix",
    "This song is beautiful",
    "Perfect mood",
    "Definitely worth listening",
    "Relaxing music",
    "Love this video",
    "Nice flow",
    "Very good song",
    "Quality content",
    "Very immersive sound",
    "This was awesome",
    "This video is awesome",
    "Nice explanation",
    "Clean execution",
    "Nice energy",
    "Nice ambience",
    "Calming video",
    "Everything is well done",
    "You can tell this took time",
    "Nice job",
    "Voice sounds great",
    "Very clear voice",
    "Excellent song",
    "Great mastering",
    "Well chosen music",
    "Nice sound design",
    "Keeps the energy",
    "This video is excellent",
    "Nice selection",
    "Very clean mix",
    "Melody sounds great",
    "Good flow overall",
    "Nice project",
    "Energy is great",
    "This song is great",
    "Lyrics fit well",
    "Nice transitions",
    "Awesome content",
    "Learned a lot from this",
    "Clean and professional",
    "High quality release",
    "Unique sound",
    "Great for driving",
    "Good breakdown",
    "Watched the whole thing",
    "Excellent sound",
    "High quality production",
    "Production value is high",
    "Always great content",
    "Clean sound",
    "Very consistent",
    "Great video",
    "Really well done",
    "Very replayable",
    "Great execution",
    "Clean structure",
    "This has nice vibes",
    "High quality video",
    "Chill vibe",
    "Nice harmonies",
    "Well produced",
    "Mix sounds great",
    "Perfect energy",
    "Quality presentation",
    "Nicely put together",
    "Good stuff",
    "Very polished production",
    "Great rhythm",
    "Nice attention to detail",
    "Explained very well",
    "Nice vocals",
    "So relaxing",
    "Lyrics are nice",
    "Excellent DJ mix",
    "This taught me a lot",
    "Great delivery",
    "Well paced and clear",
    "Really appreciate this",
    "Ambient sound is nice",
    "Yet another great video",
    "Underrated track",
    "Fantastic track",
    "Front to back solid",
    "This track is great",
    "I enjoyed this video",
    "Beautiful song",
    "Great mix",
    "This deserves more plays",
    "Time well spent",
    "This is awesome overall",
    "Great vibes",
    "High level production",
    "Solid style",
    "Great information",
    "Great upload",
    "Solid playlist",
    "Really well put together",
    "Nice choice of music",
    "Really enjoyed watching",
    "Great style",
    "Really fun to watch",
    "This deserves more attention",
    "Very chill",
    "Very nice voice",
    "Solid editing",
    "Nice audio quality",
    "Drum groove is nice",
    "Well explained",
    "High effort video",
    "Nice delivery",
    "Fantastic song",
    "Well delivered",
    "Excellent work overall",
    "Clear and concise",
    "Really well done overall",
    "Great balance",
    "Great lyrics",
    "Very well balanced",
    "Nice breakdown",
    "Very well produced",
    "Crisp sound",
    "Songwriting is solid",
    "This deserves more listeners",
    "Love this channel",
    "Always quality music",
    "Good upload",
    "Great composition",
    "Nice bass",
    "Solid execution",
    "Enjoyed every minute",
    "Very easy to listen to",
    "Everything is well explained",
    "The vibes are perfect",
    "Clean work overall",
    "Solid vocals",
    "Amazing production",
    "Well designed sound",
    "Thanks for the info",
    "This is impressive",
    "Modern sound",
    "Happy I found this",
    "Good visuals",
    "Quality work",
    "Solid mix",
    "Great melody",
    "Simple and helpful",
    "Super enjoyable",
    "Relaxing track",
    "Solid stuff",
    "Appreciate the upload",
    "Clean work",
    "Nice pacing overall",
    "Nice melody",
    "Nice editing",
    "This song is smooth",
    "Soundscape is great",
    "Music fits well",
    "Excellent work",
    "Better than expected",
    "Professional looking",
    "Thanks for the music",
    "This track is amazing",
    "Calming music",
    "Nicely crafted",
    "Pleasantly surprised",
    "Nice vibes",
    "Great harmony",
    "Straightforward explanation",
    "Very immersive",
    "Easy to get into",
    "Production is clean",
    "Great low end",
    "Flow sounds good",
    "Clearly well thought out",
    "Hits the right mood",
    "Good watch",
    "Solid bass",
    "Perfect chill music",
    "Timeless sound",
    "Nice DJ mix",
    "Great effort",
    "Excellent clarity",
    "Excellent execution",
    "Very informative",
    "This is very informative",
    "Professional quality",
    "Worth the time",
    "Distinct sound",
    "Extremely helpful",
    "Very nice video",
    "Very well done",
    "This was worth it",
    "Perfect background music",
    "Nice take on the genre",
    "Very cohesive album",
    "Really helpful video",
    "Everything looks great",
    "Nice narration",
    "Never disappoints",
    "Great project",
    "Everything flows nicely",
    "Overall impressive",
    "Much appreciated",
    "Nice playlist",
    "Great visuals",
    "This is interesting",
    "A lot of effort here",
    "Fantastic video",
    "Very clear and helpful",
    "Well paced",
    "Solid listen",
    "Great vocal performance",
    "Learned something new",
    "Nice watch",
    "Lovely song",
    "Well composed",
    "Harmony is nice",
    "Worth watching",
    "Good track selection",
    "Solid video",
    "Super impressive",
    "Good pacing",
    "Really nice vibe",
    "Flow is clean",
    "Very well presented",
    "Excellent arrangement",
    "Very well arranged",
    "Clean editing",
    "This track hits",
    "Good rhythm",
    "Well arranged",
    "Great atmosphere",
    "Very polished overall",
    "Excellent track",
    "Well balanced",
    "Very smooth",
    "Overall well done",
    "Learned a lot",
    "Clearly high effort",
    "Great sound design",
    "Nice beat",
    "Great mix overall",
    "Clean mix",
    "Great take on the genre",
    "Smooth delivery",
    "Worth the listen",
    "Very cohesive project",
    "Pleasant voice",
    "Solid project",
    "Nice balance",
    "Solid album",
    "Bass sounds great",
    "Nice effort",
    "Beat is smooth",
    "Visuals are great",
    "Well edited",
    "Very detailed",
    "Nice mood",
    "Happy this showed up",
    "Great work overall",
    "This track goes hard",
    "Excellent balance",
    "Great ambience",
    "Very well curated",
    "So chill",
    "This is nicely explained",
    "Appreciate the content",
    "Well done work",
    "Quality stuff",
    "This is great overall",
    "Nice clarity",
    "Very interesting",
    "Great job",
    "Good delivery",
    "Great editing",
    "Solid work overall",
    "Carefully made",
    "Sound is great",
    "This video is amazing",
    "A lot of care went into this",
    "Classic sound",
    "Very enjoyable",
    "This was really good",
    "High quality work",
    "This was excellent",
    "Great flow",
    "Very clean sound",
    "Nice mastering",
    "Playlist is great",
    "Good attention to detail",
    "Nicely detailed",
    "Very tasteful",
    "Excellent flow",
    "Very easy to understand",
    "Did not disappoint",
    "Nice upload",
    "Solid production",
    "Nice clear explanation",
    "Amazing song overall",
    "Executed well",
    "This song hits hard",
    "This was a great video",
    "Good effort",
    "Great sound",
    "Well detailed",
    "Balanced sound",
    "Consistently good music",
    "Great musicality",
    "Impressive video",
    "Very enjoyable video",
    "Love this song",
    "Very creative",
    "High production quality",
    "Very clear narration",
    "Thanks for making this",
    "Solid sound",
    "Chill vibes",
    "Very chill track",
    "Very well edited",
    "Amazing sound",
    "Well put together album",
    "Beat is great",
    "Clear voice",
    "Genre done well",
    "Great work",
    "Amazing content",
    "Appreciate the work",
    "Very thoughtful",
    "Smooth and clean",
    "Vocal delivery is nice",
    "High quality content",
    "Good information",
    "Nice background music",
    "Fun to watch",
    "Style fits well",
    "Nice flow throughout",
    "Could listen on repeat",
    "Beautiful track",
    "Extremely informative",
    "Great presentation",
    "Underrated video",
    "Sets the tone nicely",
    "Great narration",
    "Nice vocal tone",
    "Nice mix",
    "Very smooth flow",
    "This was enjoyable",
    "Arrangement flows nicely",
    "Low end sounds good",
    "Clear explanation",
    "High quality track",
    "Great production",
    "Vocals are smooth",
    "Moody atmosphere",
    "Always a good listen",
    "Consistent quality",
    "Great song overall",
    "Nicely produced",
    "Well crafted",
    "Album flows nicely",
    "Really enjoyed this",
    "Clear sound",
    "Another great video",
    "This deserves more views",
    "This track is beautiful",
    "Great attention to detail",
    "Great mood",
    "This is solid",
    "Editing is solid",
    "Solid groove",
    "Engaging from start to finish",
    "Nicely composed",
    "Overall very impressive",
    "Nice groove",
    "Clean and smooth",
    "Good audio",
    "Really good content",
    "Love the vibe",
    "Everything fits well",
    "Great for studying",
    "This has great vibes",
    "Very nice work",
    "Great for working",
    "Always delivers",
    "Glad this showed up",
    "This song is clean",
    "Excellent production",
    "Professional sound",
    "Excellent job",
    "Professional work",
    "Clean transitions",
    "Keeps getting better",
    "Relaxing video",
    "Great clarity",
    "Chords sound great",
    "Simple and clear",
    "Nice visuals overall",
    "Well thought out",
    "Amazing vibes",
    "Great flow overall",
    "Quality channel",
    "Great vibe",
    "Clean beat",
    "Fresh sound",
    "Very well explained",
    "Appreciate the effort",
    "Perfect vibes",
    "Really good video",
    "Top quality content",
    "Perfect for the background",
    "Nice composition",
    "Clean visuals",
    "Excellent breakdown",
    "This is well made",
    "Super engaging",
    "Very original",
    "Perfect mix",
    "Maintains a great vibe",
    "Thanks for sharing",
    "Production sounds great",
    "Great for relaxing",
    "Nice vibe",
    "Thanks for sharing this",
    "Clear presentation",
    "Solid channel",
    "Very engaging",
    "Thoughtful video",
    "Nice track selection",
    "Really clear explanation",
    "Excellent mix",
    "This song is amazing",
    "Excellent watch",
    "Solid watch",
    "Excellent composition",
    "This explains things well",
    "Very well written",
    "Amazing video",
    "Good structure",
    "Overall great video",
    "Nice work",
    "Excellent editing",
    "Clear and helpful video",
    "Nicely executed",
    "Super helpful",
    "Well put together project",
    "Quality production",
    "Production is great",
    "Transitions are smooth",
    "Excellent video",
    "Solid upload",
    "Very polished",
    "Solid content",
    "Smooth transitions",
    "Flows nicely",
    "This track is fire",
    "Solid mastering",
    "Timeless track",
    "Overall great track",
    "Very well structured",
    "Super interesting",
    "This is quality",
    "This is clear and simple",
    "Great watch",
    "Calming track",
    "Appreciate this video",
    "Everything is well structured",
    "Well done",
    "Well made video",
    "This helped a lot",
    "Good energy",
    "Great flow throughout",
    "Amazing beat",
    "Really good track",
    "Very professional",
    "Straight to the point",
    "Awesome stuff",
]

AI_KEYWORDS = [
    "ai generated",
    "ai generated content",
    "ai generated music",
    "ai generated video",
    "ai generated visuals",
    "ai generated art",
    "ai generated animation",
    "ai generated soundtrack",
    "ai generated background music",
    "ai generated beat",
    "ai generated track",
    "ai generated mix",
    "ai generated album",
    "ai generated playlist",
    "ai generated sound",
    "ai generated audio",
    "ai generated imagery",
    "ai generated graphics",
    "ai generated visuals loop",
    "ai generated video loop",
    "ai music",
    "ai music generation",
    "ai music generator",
    "ai music tool",
    "ai music software",
    "ai music platform",
    "ai composed music",
    "ai composed track",
    "ai composed song",
    "ai produced music",
    "ai assisted music",
    "ai assisted production",
    "ai assisted composition",
    "artificial intelligence",
    "artificial intelligence music",
    "artificial intelligence audio",
    "artificial intelligence visuals",
    "artificial intelligence generated",
    "artificial intelligence content",
    "artificial intelligence tools",
    "artificial intelligence software",
    "created with ai",
    "made with ai",
    "produced with ai",
    "generated with ai",
    "composed with ai",
    "built with ai",
    "powered by ai",
    "using ai tools",
    "using artificial intelligence",
    "stable audio",
    "stable audio music",
    "stable audio generation",
    "stable audio ai",
    "stable audio soundtrack",
    "suno",
    "suno ai",
    "suno generated",
    "suno music",
    "suno ai music",
    "made with suno",
    "created with suno",
    "udio",
    "udio ai",
    "udio generated",
    "udio music",
    "udio ai music",
    "made with udio",
    "created with udio",
    "ai sound generator",
    "ai audio generator",
    "ai voice generator",
    "ai instrumental generator",
    "ai beat generator",
    "ai loop generator",
    "ai ambient generator",
    "text to music",
    "text to audio",
    "text to sound",
    "text to song",
    "prompt to music",
    "prompt based music",
    "prompt generated audio",
    "prompt generated music",
    "music generator",
    "audio generator",
    "sound generator",
    "beat generator",
    "track generator",
    "song generator",
    "music creation ai",
    "audio creation ai",
    "no copyright",
    "no copyright music",
    "no copyright audio",
    "no copyright soundtrack",
    "no copyright background music",
    "royalty free",
    "royalty free music",
    "royalty free audio",
    "royalty free soundtrack",
    "royalty free ai music",
    "royalty free ai audio",
    "copyright free",
    "copyright free music",
    "copyright free audio",
    "copyright free soundtrack",
    "copyright free ai music",
    "ai visuals",
    "ai video",
    "ai animation",
    "ai video generator",
    "ai visuals generator",
    "ai background visuals",
    "ai video loop",
    "ai generated loop",
    "ai visualizer",
    "ai music visualizer",
    "text to video",
    "prompt to video",
    "text to visuals",
    "prompt based visuals",
    "ai art",
    "ai artwork",
    "ai digital art",
    "ai generated art",
    "ai generated images",
    "ai generated graphics",
    "generative ai",
    "generative ai music",
    "generative ai audio",
    "generative ai visuals",
    "generative music",
    "generative audio",
    "generative visuals",
    "machine generated music",
    "machine generated audio",
    "machine generated visuals",
    "algorithm generated music",
    "algorithmic music",
    "neural network music",
    "neural audio generation",
    "neural sound synthesis",
    "ai soundtrack",
    "ai background music",
    "ai cinematic music",
    "ai ambient music",
    "ai lo fi music",
    "ai electronic music",
    "ai experimental music",
    "fully ai generated",
    "100 percent ai generated",
    "entirely ai generated",
    "ai only music",
    "ai only visuals",
    "ai music video",
    "ai generated music video",
    "ai animated music video",
    "ai content",
    "ai media",
    "ai creative tools",
    "ai creative software",
    "ai powered creativity",
    "automatic music generation",
    "automated music creation",
    "automated audio generation",
    "synthetic music",
    "synthetic audio",
    "synthetic sound",
    "computer generated music",
    "computer generated audio",
    "computer generated visuals",
]
